version: "3.8"
services:
  # Authelia
  authelia:
    container_name: authelia
    image: docker.io/authelia/authelia:latest
    restart: unless-stopped
    volumes:
      - /srv/authelia/config:/config
    #    ports:
    #      - 9091:9091
    networks:
      - authelia
      - proxy
      - redis
    labels:
      # Adding this label means this container should be stopped while it's being backed up:
      - docker-volume-backup.stop-during-backup=true
networks:
  authelia:
    name: authelia
    ipam:
      config:
        - subnet: 172.22.2.0/24
  proxy:
    external: true
  redis:
    external: true